### ISSUE TITLE
image 파일 경로 문제

### ISSUE THREAD

**Issue by sumhillj** [Joo-Nick/OSS-Project#10]
<img width="1440" alt="스크린샷 2024-06-02 오전 2 16 16" src="https://github.com/Joo-Nick/OSS-Project/assets/127292146/5b5e403e-19da-4f24-be0e-c22a360b57bc">

첨부 사진에서 나온 것처럼, 이미지 src 경로 문제로 dino_step3_final.py가 실행되지 않는 에러가 계속 발생합니다. 팀원들 간 로컬 운영체제가 Windows/MacOS로 달라서일수도 있고, 파일 경로를 상대 경로로 지정하여 생긴 문제일 수도 있습니다. 현재 다양한 방법을 서치하며 해결중입니다.

**Comment by Joo-Nick** [comment]
경로 지정을 명확하게 하면 되는 경우도 있다고 합니다.
C:/Users/ 이렇게 해서 최상위부터 경로 지정해서 내려오는 걸로 바꿔서 해봐요!

**Comment by sumhillj** [comment]
> 경로 지정을 명확하게 하면 되는 경우도 있다고 합니다. C:/Users/ 이렇게 해서 최상위부터 경로 지정해서 내려오는 걸로 바꿔서 해봐요!

제안해주신대로 절대 경로 지정도 좋은 해결방법이 될 수 있다고 알고 있습니다. 해결은 다른 방식으로 했지만, 도움 감사합니다!
