### ISSUE TITLE
obstalce의 Tree 위치 변경

### ISSUE THREAD

**Issue by cjs5662** [Joo-Nick/OSS-Project#5]
화면의 배경 추가와 이에 맡게 dino의 위치 변경으로 인해 tree가 dino와 충돌할 수 없는 위치에서 생성됩니다.
이를 배경과 공룡의 생성 위치에 알맞게 수정하겠습니다.

**Comment by Joo-Nick** [comment]
확인했습니다. 추후에 충돌 구현을 위해서 rect 사용해야 할 것 같습니다!

**Comment by sumhillj** [comment]
확인했습니다!

**Comment by e2guana** [comment]
확인했습니다
