### ISSUE TITLE
obstacle.py에 작성된 장애물 클래스 계층 구조 도입

### ISSUE THREAD

**Issue by cjs5662** [Joo-Nick/OSS-Project#6]
현재 Obstacle.py에 작성된 장애물들이 단일 클래스로 구현되어 있습니다. 이를 다양한 종류의 장애물을 효율적으로 관리하고 유연성과 확장성을 높이기 위해 클래스 계층 구조를 도입하려고 합니다. 

수정할 내용
1. `Obstacle` 부모 클래스 생성
2. 기존 장애물 클래스를 `Obstacle` 클래스의 자식으로 알맞게 변경

**Comment by Joo-Nick** [comment]
추가 장애물 생성 시 도움이 될 것 같습니다

**Comment by sumhillj** [comment]
확인했습니다. 확실히 단일 계층보다는 구분이 명확해서 좋을 것 같네요

**Comment by e2guana** [comment]
확인했습니다
