### ISSUE TITLE
장애물 관련 변경사항

### ISSUE THREAD

**Issue by Joo-Nick** [Joo-Nick/OSS-Project#9]
1. 현재 장애물의 로직으로는 생성된 장애물이 화면 밖으로 사라져야 새로운 것이 나와 규칙적이어서 재미가 부족.
-> 랜덤으로 생성이 되도록 로직 변경 필요.
2. 날아다니는 장애물의 경우 지그재그 패턴으로 날아다니게 되어 있으나 게임을 실행시 불가피하게 반드시 충돌.
-> 제일 처음에 y 값을 랜덤한 변수로 받고 그 y값을 고정한 상태로(일자로 날아가게) 움직이도록 변경. 
-> 이렇게 하게 된다면 구현 한 슬라이딩 기술을 사용가능.
3. 장애물의 종류 증가 필요.
-> 현재는 나무가 하나만 나오는데 이것을 나무 2개 혹은 3개를 이어 붙여 게임의 난이도 증가.

**Comment by cjs5662** [comment]
문제점 및 개선사항 반영해 수정하겠습니다. 그리고 3번을 수행하면서 게임전반의 이미지와 유사한 장애물 이미지를 찾아서 이밎도 변경하겠습니다.

**Comment by e2guana** [comment]
함정 형태의 바닥 장애물을 추가했는데 랜덤성을 부여하는 과정 중에 자꾸 문제가 일어나서 수정하고 있습니다
